fix #5 - wget errors set critical

diff --git a/check_website b/check_website
--- a/check_website
+++ b/check_website
@@ -216,32 +216,33 @@ if [ $status -eq 0 ] ; then
 else
   case $status in
     1)
-      echo "${header} Generic error code: $status - ${url}"
+      echo "${header} CRITICAL: Generic error code ($status) - ${url}"
       ;;
     2)
-      echo "${header} Parse error: $status - ${url}"
+      echo "${header} CRITICAL: Parse error ($status) - ${url}"
       ;;
     3)
-      echo "${header} File I/O error: $status - ${url}"
+      echo "${header} CRITICAL: File I/O error ($status) - ${url}"
       ;;
     4)
-      echo "${header} Network failure: $status - ${url}"
+      echo "${header} CRITICAL: Network failure ($status) - ${url}"
       ;;
     5)
-      echo "${header} SSL verification failure: $status - ${url}"
+      echo "${header} CRITICAL: SSL verification failure ($status) - ${url}"
       ;;
     6)
-      echo "${header} Authentication failure: $status - ${url}"
+      echo "${header} CRITICAL: Authentication failure ($status) - ${url}"
       ;;
     7)
-      echo "${header} Protocol errors: $status - ${url}"
+      echo "${header} CRITICAL: Protocol errors ($status) - ${url}"
       ;;
     8)
-      echo "${header} Server issued an error response: $status - ${url}"
+      echo "${header} CRITICAL: Server issued an error response ($status) - ${url}"
       ;;
     *)
       echo "${header} UNKNOWN: $status - ${url}"
+      exit 3
       ;;
   esac
-  exit 3
+  exit 2
 fi
